services:
  cassandra:
    image: cassandra:4
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "0.0.0.0:9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TheHive
    volumes:
      - cassandradata:/var/lib/cassandra
    networks:
      - SOC_NET
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    restart: unless-stopped
    mem_limit: 512m
    ports:
      - "0.0.0.0:9205:9205"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=hive
      - http.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    networks:
      - SOC_NET

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: ["minio", "server", "/data", "--console-address", ":9002"]
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "0.0.0.0:9002:9002"
      - "0.0.0.0:9005:9000"
    volumes:
      - miniodata:/data
    networks:
      - SOC_NET

  thehive:
    image: strangebee/thehive:5.2
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
      - minio
    mem_limit: 1500m
    ports:
      - "0.0.0.0:9000:9000"
    environment:
      - JVM_OPTS=-Xms1024M -Xmx1024M
    command:
      - --secret
      - "lab123456789"
      - --cql-hostnames
      - cassandra
      - --index-backend
      - elasticsearch
      - --es-hostnames
      - elasticsearch
      - --s3-endpoint
      - http://minio:9000
      - --s3-access-key
      - minioadmin
      - --s3-secret-key
      - minioadmin
      - --s3-use-path-access-style
    volumes:
      - thehivedata:/etc/thehive
    networks:
      - SOC_NET

volumes:
  miniodata:
  cassandradata:
  elasticsearchdata:
  thehivedata:

networks:
  SOC_NET:
    driver: bridge
